#ifndef SOPNET_CATMAIND_PERSISTENCE_LOCAL_SOLUTION_STORE_H__
#define SOPNET_CATMAIND_PERSISTENCE_LOCAL_SOLUTION_STORE_H__

#include "SolutionStore.h"

class LocalSolutionStore : public SolutionStore {};

#endif // SOPNET_CATMAIND_PERSISTENCE_LOCAL_SOLUTION_STORE_H__

